# Generated by Django 3.2.13 on 2022-04-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_blood_donated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
