# Generated by Django 3.2.13 on 2022-04-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapi', '0004_auto_20220430_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequirement',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequirement',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
