# Generated by Django 3.2.13 on 2022-04-30 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloodapi', '0005_auto_20220430_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequirement',
            name='profile',
        ),
        migrations.AddField(
            model_name='bloodrequirement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
